spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/yeying_social?useSSL=false&useUnicode=true&characterEncoding=utf-8&allowPublicKeyRetrieval=true
    username: root
    password: "${MYSQL_PASSWORD:pingpong}"
  data:
    redis:
      host: localhost
      port: 6379
      password: "${REDIS_PASSWORD:YourStrongPassword123!}"

minio:
  endpoint: http://127.0.0.1:9000 #内网地址
  domain: http://127.0.0.1:9000  #外网访问地址
  accessKey: "${MINIO_ACCESS_KEY:minio}"
  secretKey: "${MINIO_SECRET_KEY:08abc206-460e-4a1e-83f9-b8613502f263}"
  bucketName: yeying-social
  imagePath: image
  filePath: file
  videoPath: video
  expireIn: 180 # 文件过期时间,单位:天
